apiVersion: v1
kind: Service
metadata:
  # имя сервиса 
  name: {{ include "clickhouse.fullname" . }}
spec:
  type: ClusterIP
  selector:
    # выбирает поды с меткой app=mych-clickhouse 
    app: {{ include "clickhouse.fullname" . }}
  ports:
    # http-интерфейс clickhouse
    - name: http
      port: 8123
      targetPort: 8123
      protocol: TCP
    # нативный tcp-порт 
    - name: tcp
      port: 9000
      targetPort: 9000
      protocol: TCP